services:
  - type: web
    name: alphagenome-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: ALPHAGENOME_API_KEY
        value: AIzaSyAd8VEbbDBGpQoPGK4v8LZzdaGlgBh2kaE
    autoDeploy: true
    healthCheckPath: /health
    region: oregon